# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'plugins/xqaf/ui_options_xqaf.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_XQAFOptionsPage(object):
    def setupUi(self, XQAFOptionsPage):
        XQAFOptionsPage.setObjectName("XQAFOptionsPage")
        XQAFOptionsPage.resize(602, 555)
        self.vboxlayout = QtWidgets.QVBoxLayout(XQAFOptionsPage)
        self.vboxlayout.setContentsMargins(9, 9, 9, 9)
        self.vboxlayout.setSpacing(6)
        self.vboxlayout.setObjectName("vboxlayout")
        self.groupBox = QtWidgets.QGroupBox(XQAFOptionsPage)
        self.groupBox.setObjectName("groupBox")
        self.vboxlayout1 = QtWidgets.QVBoxLayout(self.groupBox)
        self.vboxlayout1.setContentsMargins(9, 9, 9, 9)
        self.vboxlayout1.setSpacing(2)
        self.vboxlayout1.setObjectName("vboxlayout1")
        self.xqaf_compression_disabled_note = QtWidgets.QFrame(self.groupBox)
        self.xqaf_compression_disabled_note.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.xqaf_compression_disabled_note.setObjectName("xqaf_compression_disabled_note")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.xqaf_compression_disabled_note)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_2 = QtWidgets.QFrame(self.xqaf_compression_disabled_note)
        self.frame_2.setStyleSheet("QFrame { background-color: #ffc107; color: black }\n"
"QCheckBox { color: black }")
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.verticalLayout_3.addWidget(self.frame_2)
        spacerItem = QtWidgets.QSpacerItem(1, 6, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem)
        self.vboxlayout1.addWidget(self.xqaf_compression_disabled_note)
        self.xqaf_compression_mode = QtWidgets.QGroupBox(self.groupBox)
        self.xqaf_compression_mode.setObjectName("xqaf_compression_mode")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.xqaf_compression_mode)
        self.verticalLayout.setObjectName("verticalLayout")
        self.xqaf_compression_keep = QtWidgets.QRadioButton(self.xqaf_compression_mode)
        self.xqaf_compression_keep.setObjectName("xqaf_compression_keep")
        self.verticalLayout.addWidget(self.xqaf_compression_keep)
        self.xqaf_compression_compress = QtWidgets.QRadioButton(self.xqaf_compression_mode)
        self.xqaf_compression_compress.setObjectName("xqaf_compression_compress")
        self.verticalLayout.addWidget(self.xqaf_compression_compress)
        self.xqaf_compression_none = QtWidgets.QRadioButton(self.xqaf_compression_mode)
        self.xqaf_compression_none.setObjectName("xqaf_compression_none")
        self.verticalLayout.addWidget(self.xqaf_compression_none)
        self.vboxlayout1.addWidget(self.xqaf_compression_mode)
        self.xqaf_update_gapless_flag = QtWidgets.QCheckBox(self.groupBox)
        self.xqaf_update_gapless_flag.setObjectName("xqaf_update_gapless_flag")
        self.vboxlayout1.addWidget(self.xqaf_update_gapless_flag)
        self.vboxlayout.addWidget(self.groupBox)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.vboxlayout.addItem(spacerItem1)

        self.retranslateUi(XQAFOptionsPage)
        QtCore.QMetaObject.connectSlotsByName(XQAFOptionsPage)

    def retranslateUi(self, XQAFOptionsPage):
        _translate = QtCore.QCoreApplication.translate
        self.groupBox.setTitle(_translate("XQAFOptionsPage", "Extended QOA Format"))
        self.label.setText(_translate("XQAFOptionsPage", "Support for XQAF files with compressed tags is disabled. The Python zstandard module is unavailable."))
        self.xqaf_compression_mode.setTitle(_translate("XQAFOptionsPage", "Tag compression"))
        self.xqaf_compression_keep.setText(_translate("XQAFOptionsPage", "Keep compression as is"))
        self.xqaf_compression_compress.setText(_translate("XQAFOptionsPage", "Always compress tags"))
        self.xqaf_compression_none.setText(_translate("XQAFOptionsPage", "Never compress tags"))
        self.xqaf_update_gapless_flag.setText(_translate("XQAFOptionsPage", "Update the gapless flag on saving"))
